name: Semgrep

on: 

    pull_request: {}

    workflow_dispatch: {}

    push:
       branches:
            - main
            - master
       paths:
            - .github/workflows/semgrep.yml

    schedule:
        - cron: '0 12 * * *' #sets semgrep to scan the code at 12noon
        - cron: '0 18 * * *' #sets semgrep to scan the code at 6pm daily
jobs:
    semgrep:

        name: semgrep/ci
        runs-on: ubuntu-latest

        container:
            image: semgrep/semgrep

        if: (github.actor != 'dependent[bot]')
        steps:
           - uses: actions/checkout@v4
           - run: semgrep ci
             env:
              SEMGREP_APP_TOKEN: ${{secrets.SEMGREP_APP_TOKEN}}

